### ISSUE TITLE
Library Manager issue

### ISSUE THREAD

**Issue by LaudixGit** [khoih-prog/AsyncWebServer_WT32_ETH01#4]
### Describe the bug

Installation of the library prompts for dependencies that do not exist.

### Steps to Reproduce

I reimaged my RPi4 with the latest RaspiOS and installed Arduino IDE 1.8.19
then attempted to install this library
When 'install all' button is clicked, the install fails with obscure error.
![image](https://user-images.githubusercontent.com/58885245/205426995-92c2ed45-708d-455f-adae-31771dbb7973.png)

Installing library "only" succeeds

### Expected behavior

If there are no dependencies the popup should not appear

### Actual behavior

Unneeded dialog box appears, and the obvious option fails.

### Information

Please ensure to specify the following:

* Arduino IDE version1.8.19
* Board Core Version ESP32 core v2.0.5
WT32_ETH01 board

**Comment by LaudixGit** [comment]
Note: this was occurring a month ago too, but I didn't think to report it since it only happens once, during library installation

**Comment by khoih-prog** [comment]
Hi @LaudixGit 

You have to install `AsyncTCP` manually and remove

https://github.com/khoih-prog/AsyncWebServer_WT32_ETH01/blob/702f7fb744dbb5a978fd995ed17b187991d3f48a/library.properties#L11

The reason is that nobody cares to publish [**AsyncTCP**](https://github.com/me-no-dev/AsyncTCP) into Arduino Library Manager, only to PIO. But I just leave the dependency there for completion as I didn't see no harm.
